app = "api-peliculas-jose"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 3
    timeout = "2s"

# 🔧 Auto-suspend configuration
# Fly.io suspende automáticamente las máquinas cuando no hay tráfico HTTP
# Pero aquí reforzamos el comportamiento usando auto_stop y auto_start.

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  auto_start = true
  auto_stop = true
  stop_timeout = "1m"
