# fly.toml file generated for peliprex-pe-v2
app = "peliprex-pe-v2"
primary_region = "gru"  # Región válida en Fly.io (São Paulo, Brasil)

[build]
  image = "node:18-bullseye"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0
